# Generated by Django 2.2.5 on 2019-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20191106_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='forMainpage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(max_length=1288, verbose_name='상품코드'),
        ),
    ]
