# Generated by Django 2.2.5 on 2019-11-25 09:46

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20191117_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to=API.models.MainpageImage.date_upload_to)),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'API_mainImage',
            },
        ),
    ]
