# Generated by Django 2.2.5 on 2019-11-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_mainpageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageimage',
            options={'verbose_name': 'MainImage', 'verbose_name_plural': 'MainImages'},
        ),
    ]
