# Generated by Django 2.2.6 on 2019-12-02 07:21

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20191125_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='모델명')),
                ('photo_00', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_01', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_02', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_03', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_04', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_05', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_06', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_07', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
                ('photo_08', models.ImageField(upload_to=API.models.Lookbook.data_upload_to)),
            ],
            options={
                'verbose_name': '모델명',
                'verbose_name_plural': '사진들',
                'db_table': 'API_lookbook',
            },
        ),
    ]
