# Generated by Django 2.2.5 on 2019-12-02 11:02

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20191125_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to=API.models.LookbookImage.date_upload_to)),
                ('modelName', models.CharField(max_length=100)),
                ('isMain', models.BooleanField()),
            ],
            options={
                'verbose_name': 'LookbookImage',
                'verbose_name_plural': 'LookbookImages',
                'db_table': 'API_LookbookImage',
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(max_length=1288),
        ),
    ]
