# Generated by Django 2.2.6 on 2019-12-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_lookbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookbook',
            old_name='name',
            new_name='person',
        ),
    ]
