# Generated by Django 2.2.5 on 2019-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20191202_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookbookimage',
            name='modelName',
        ),
        migrations.AddField(
            model_name='lookbookimage',
            name='modelNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
