# Generated by Django 2.2.6 on 2019-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20191202_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertitle', models.CharField(max_length=200)),
                ('usercontent', models.TextField()),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
